[tool.poetry]
name = "localproject"
version = "0.1.0"
description = ""
authors = ["Danila Komolov <inostranec1.1@yandex.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.13"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
